services:
  - type: web
    name: webrtc-private-room
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    repo: https://github.com/your/repo-here
